name: Selenium Test

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2

        - name: Install Firefox
          run: |
            sudo apt-get update
            sudo apt-get install -y firefox
    
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10.12'
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Run Selenium Test
          run: |
            python main.py