name: Selenium Test

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
        
        - name: Obter IP privado da máquina
          run: |
           IP_PRIVADO=$(hostname -I)
           echo "O IP privado do runner é: $IP_PRIVADO"
        # - name: Install and run
        #   run: |
        #     docker compose up --abort-on-container-exit

        # - name: Upload screenshot
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: screenshot
        #     path: screenshot.png