name: Selenium Test

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
    
        - name: Install and run
          run: |
            docker compose up --abort-on-container-exit

        - name: Upload screenshot
          uses: actions/upload-artifact@v4
          with:
            name: screenshot
            path: screenshot.png